# Generated by Django 4.0 on 2023-11-28 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='rel',
        ),
        migrations.AddField(
            model_name='post',
            name='word',
            field=models.ManyToManyField(related_name='post', to='post.Word'),
        ),
    ]
