# Generated by Django 4.0 on 2023-11-28 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_word_remove_post_rel_post_word'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='word',
            index=models.Index(fields=['word'], name='post_word_word_943b4d_idx'),
        ),
    ]
